/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIdRouteImport } from './routes/status.$id'
import { Route as ManageIdRouteImport } from './routes/manage.$id'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedManageBookingIdRouteImport } from './routes/_authenticated/manage-booking.$id'
import { Route as ApiPublicHooksBookingRemindersRouteImport } from './routes/api/public/hooks/booking-reminders'
import { Route as ApiPublicBookingPdfIdRouteImport } from './routes/api/public/booking-pdf.$id'
import { Route as ApiPublicBookingIcsIdRouteImport } from './routes/api/public/booking-ics.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIdRoute = StatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdRoute = ManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageBookingIdRoute =
  AuthenticatedManageBookingIdRouteImport.update({
    id: '/manage-booking/$id',
    path: '/manage-booking/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksBookingRemindersRoute =
  ApiPublicHooksBookingRemindersRouteImport.update({
    id: '/api/public/hooks/booking-reminders',
    path: '/api/public/hooks/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingPdfIdRoute = ApiPublicBookingPdfIdRouteImport.update({
  id: '/api/public/booking-pdf/$id',
  path: '/api/public/booking-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingIcsIdRoute = ApiPublicBookingIcsIdRouteImport.update({
  id: '/api/public/booking-ics/$id',
  path: '/api/public/booking-ics/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/manage/$id': typeof ManageIdRoute
  '/status/$id': typeof StatusIdRoute
  '/manage-booking/$id': typeof AuthenticatedManageBookingIdRoute
  '/api/public/booking-ics/$id': typeof ApiPublicBookingIcsIdRoute
  '/api/public/booking-pdf/$id': typeof ApiPublicBookingPdfIdRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/manage/$id': typeof ManageIdRoute
  '/status/$id': typeof StatusIdRoute
  '/manage-booking/$id': typeof AuthenticatedManageBookingIdRoute
  '/api/public/booking-ics/$id': typeof ApiPublicBookingIcsIdRoute
  '/api/public/booking-pdf/$id': typeof ApiPublicBookingPdfIdRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/manage/$id': typeof ManageIdRoute
  '/status/$id': typeof StatusIdRoute
  '/_authenticated/manage-booking/$id': typeof AuthenticatedManageBookingIdRoute
  '/api/public/booking-ics/$id': typeof ApiPublicBookingIcsIdRoute
  '/api/public/booking-pdf/$id': typeof ApiPublicBookingPdfIdRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/my-bookings'
    | '/manage/$id'
    | '/status/$id'
    | '/manage-booking/$id'
    | '/api/public/booking-ics/$id'
    | '/api/public/booking-pdf/$id'
    | '/api/public/hooks/booking-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/my-bookings'
    | '/manage/$id'
    | '/status/$id'
    | '/manage-booking/$id'
    | '/api/public/booking-ics/$id'
    | '/api/public/booking-pdf/$id'
    | '/api/public/hooks/booking-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/my-bookings'
    | '/manage/$id'
    | '/status/$id'
    | '/_authenticated/manage-booking/$id'
    | '/api/public/booking-ics/$id'
    | '/api/public/booking-pdf/$id'
    | '/api/public/hooks/booking-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ManageIdRoute: typeof ManageIdRoute
  StatusIdRoute: typeof StatusIdRoute
  ApiPublicBookingIcsIdRoute: typeof ApiPublicBookingIcsIdRoute
  ApiPublicBookingPdfIdRoute: typeof ApiPublicBookingPdfIdRoute
  ApiPublicHooksBookingRemindersRoute: typeof ApiPublicHooksBookingRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$id': {
      id: '/status/$id'
      path: '/status/$id'
      fullPath: '/status/$id'
      preLoaderRoute: typeof StatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-booking/$id': {
      id: '/_authenticated/manage-booking/$id'
      path: '/manage-booking/$id'
      fullPath: '/manage-booking/$id'
      preLoaderRoute: typeof AuthenticatedManageBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/booking-reminders': {
      id: '/api/public/hooks/booking-reminders'
      path: '/api/public/hooks/booking-reminders'
      fullPath: '/api/public/hooks/booking-reminders'
      preLoaderRoute: typeof ApiPublicHooksBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-pdf/$id': {
      id: '/api/public/booking-pdf/$id'
      path: '/api/public/booking-pdf/$id'
      fullPath: '/api/public/booking-pdf/$id'
      preLoaderRoute: typeof ApiPublicBookingPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-ics/$id': {
      id: '/api/public/booking-ics/$id'
      path: '/api/public/booking-ics/$id'
      fullPath: '/api/public/booking-ics/$id'
      preLoaderRoute: typeof ApiPublicBookingIcsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedManageBookingIdRoute: typeof AuthenticatedManageBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedManageBookingIdRoute: AuthenticatedManageBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ManageIdRoute: ManageIdRoute,
  StatusIdRoute: StatusIdRoute,
  ApiPublicBookingIcsIdRoute: ApiPublicBookingIcsIdRoute,
  ApiPublicBookingPdfIdRoute: ApiPublicBookingPdfIdRoute,
  ApiPublicHooksBookingRemindersRoute: ApiPublicHooksBookingRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
